sudo: required

language: generic

notifications:
  email: false

services:
  - docker

before_install:
  - docker pull goofacz/omnetpp-inet-travis:latest

script:
  - docker run -i -t -e SMILE_FRAMEWORK=1 -e PROJECT_NAME=smile -v /home/travis/build/$TRAVIS_REPO_SLUG:/root/smile goofacz/omnetpp-inet-travis:latest
